/* ============================================================
   Menu data — 47 dishes across 6 categories
   ============================================================ */

const IMG = {
  kebabTortilla: "https://images.unsplash.com/photo-1633321702518-7feccafb94d5?auto=format&fit=crop&w=900&q=80",
  kebabPita:     "https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=900&q=80",
  kebabPlate:    "https://images.unsplash.com/photo-1530469912745-a215c6b256ea?auto=format&fit=crop&w=900&q=80",
  shawarma:      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80",
  falafelPita:   "https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&w=900&q=80",
  falafelBowl:   "https://images.unsplash.com/photo-1547928576-b822bc41b15a?auto=format&fit=crop&w=900&q=80",
  falafelPlate:  "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80",
  tacos:         "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=80",
  tacos2:        "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80",
  kapsalon:      "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f9d?auto=format&fit=crop&w=900&q=80",
  boxStrips:     "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=80",
  boxFries:      "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80",
  salad:         "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80",
  coke:          "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=900&q=80",
  bottle:        "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80",
  ayran:         "https://images.unsplash.com/photo-1571687949921-1306bfb24b72?auto=format&fit=crop&w=900&q=80",
  lemonade:      "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=900&q=80",
  sauce:         "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=900&q=80",
  fries:         "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=80",
};

const mockMenuCategories = [
  { id: "kebab",   label: "Kebab",        itemCount: 18, description: "The classics — pita, tortilla, plate." },
  { id: "falafel", label: "Falafel",      itemCount: 9,  description: "Hand-rolled every morning." },
  { id: "tacos",   label: "Tacos",        itemCount: 4,  description: "Soft shells, choose your spice." },
  { id: "box",     label: "Box & Plates", itemCount: 8,  description: "Built for two, or one big hunger." },
  { id: "drinks",  label: "Drinks",       itemCount: 7,  description: "Cold from the case." },
  { id: "sauces",  label: "Sauces",       itemCount: 1,  description: "Made in-house." },
];

/* ---------- Modifier group templates ---------- */
const MG = {
  kebabMeat: () => ({
    id: "meat",
    name: "Meat",
    required: true,
    min: 1, max: 1,
    options: [
      { id: "chicken", name: "Kurczak",   priceDelta: 0, default: true },
      { id: "beef",    name: "Wołowina",  priceDelta: 0 },
      { id: "mixed",   name: "Mieszane",  priceDelta: 0 },
    ],
  }),
  kebabSauce: () => ({
    id: "sauce",
    name: "Sauce",
    required: true,
    min: 1, max: 3,
    options: [
      { id: "lagodny",  name: "Łagodny",         priceDelta: 0, default: true },
      { id: "mieszany", name: "Mieszany",        priceDelta: 0 },
      { id: "ostry",    name: "Ostry",           priceDelta: 0 },
      { id: "garlic",   name: "Czosnkowy",       priceDelta: 0 },
      { id: "tahini",   name: "Tahini",          priceDelta: 0 },
    ],
  }),
  extras: () => ({
    id: "extras",
    name: "Extras",
    required: false,
    min: 0, max: 4,
    options: [
      { id: "x-cheese",   name: "Extra cheese",   priceDelta: 4 },
      { id: "x-meat",     name: "Extra meat",     priceDelta: 6 },
      { id: "halloumi",   name: "Halloumi",       priceDelta: 5 },
      { id: "no-onion",   name: "No onion",       priceDelta: 0 },
    ],
  }),
  falafelSauce: () => ({
    id: "sauce",
    name: "Sauce",
    required: true,
    min: 1, max: 2,
    options: [
      { id: "hummus",  name: "Hummus",     priceDelta: 0, default: true },
      { id: "tahini",  name: "Tahini",     priceDelta: 0 },
      { id: "garlic",  name: "Czosnkowy",  priceDelta: 0 },
      { id: "ostry",   name: "Ostry",      priceDelta: 0 },
    ],
  }),
  tacoFilling: () => ({
    id: "filling",
    name: "Filling",
    required: true,
    min: 1, max: 1,
    options: [
      { id: "chicken", name: "Kebab kurczak",  priceDelta: 0, default: true },
      { id: "beef",    name: "Kebab wołowina", priceDelta: 0 },
      { id: "falafel", name: "Falafel",        priceDelta: 0 },
      { id: "mix",     name: "Mieszane",       priceDelta: 2 },
    ],
  }),
  spiceLevel: () => ({
    id: "spice",
    name: "Spice level",
    required: true,
    min: 1, max: 1,
    options: [
      { id: "mild",    name: "Łagodny",     priceDelta: 0 },
      { id: "medium",  name: "Średni",      priceDelta: 0, default: true },
      { id: "hot",     name: "Ostry",       priceDelta: 0 },
      { id: "vhot",    name: "Bardzo ostry", priceDelta: 0 },
    ],
  }),
  drinkType: () => ({
    id: "type",
    name: "Type",
    required: true,
    min: 1, max: 1,
    options: [
      { id: "cola",     name: "Coca-Cola",      priceDelta: 0, default: true },
      { id: "cola-z",   name: "Coca-Cola Zero", priceDelta: 0 },
      { id: "sprite",   name: "Sprite",         priceDelta: 0 },
      { id: "fanta",    name: "Fanta",          priceDelta: 0 },
    ],
  }),
  drinkSize: () => ({
    id: "size",
    name: "Size",
    required: true,
    min: 1, max: 1,
    options: [
      { id: "0.33", name: "0,33 L",   priceDelta: 0, default: true },
      { id: "0.5",  name: "0,5 L",    priceDelta: 2 },
      { id: "1.0",  name: "1,0 L",    priceDelta: 4 },
    ],
  }),
};

/* ---------- Dishes ---------- */
const D = (overrides) => ({
  flags: [],
  modifierGroups: [],
  allergens: [],
  ...overrides,
});

const KEBAB = [
  D({ id: "kebab-tortilla-maly",   categoryId: "kebab", name: "Kebab Tortilla Mały",   description: "Beef + lamb mix, fresh salad, tahini sauce in a warm tortilla.",
       price: { amount: 19, currency: "PLN" }, prepMinutes: 8, calories: 620, image: { src: IMG.kebabTortilla, alt: "Small kebab tortilla wrap" },
       allergens: ["Gluten", "Sesame"],
       modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()],
       longDescription: "Our smaller tortilla — easy weekday lunch. Same meat, same bread, just less of it. Built to order in under five minutes." }),
  D({ id: "kebab-tortilla-srodni", categoryId: "kebab", name: "Kebab Tortilla Średni", description: "Beef + lamb mix, fresh salad, tahini sauce in a warm tortilla. Our most-ordered.",
       price: { amount: 24, currency: "PLN" }, flags: ["featured"], prepMinutes: 9, calories: 780, image: { src: IMG.kebabTortilla, alt: "Medium kebab tortilla wrap" },
       allergens: ["Gluten", "Sesame"],
       modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()],
       longDescription: "The size most people get — generous portion of meat shaved off the spit straight onto a fresh tortilla. The kind of thing you tell your friends about." }),
  D({ id: "kebab-tortilla-duzy",   categoryId: "kebab", name: "Kebab Tortilla Duży",   description: "Loaded version of the classic. Built for big appetites.",
       price: { amount: 28, currency: "PLN" }, prepMinutes: 9, calories: 920, image: { src: IMG.kebabTortilla, alt: "Large kebab tortilla wrap" },
       allergens: ["Gluten", "Sesame"],
       modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-pita-maly",       categoryId: "kebab", name: "Kebab Pita Mały",       description: "Soft pita, salad, the meat of your choice.",
       price: { amount: 19, currency: "PLN" }, prepMinutes: 7, calories: 540, image: { src: IMG.kebabPita, alt: "Small kebab pita" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "kebab-pita-srodni",     categoryId: "kebab", name: "Kebab Pita Średni",     description: "The pita classic — bread baked through the day.",
       price: { amount: 23, currency: "PLN" }, prepMinutes: 7, calories: 700, image: { src: IMG.kebabPita, alt: "Medium kebab pita" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-pita-duzy",       categoryId: "kebab", name: "Kebab Pita Duży",       description: "Big-pita energy. Recommended with the spicy sauce.",
       price: { amount: 27, currency: "PLN" }, prepMinutes: 8, calories: 860, image: { src: IMG.kebabPita, alt: "Large kebab pita" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-bulka",           categoryId: "kebab", name: "Kebab Bułka",           description: "Crisp Polish-style bun, kebab, slaw.",
       price: { amount: 21, currency: "PLN" }, prepMinutes: 7, calories: 660, image: { src: IMG.kebabPita, alt: "Kebab bun" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "kebab-bulka-duzy",      categoryId: "kebab", name: "Kebab Bułka Duży",      description: "Bigger bun. More of everything.",
       price: { amount: 26, currency: "PLN" }, prepMinutes: 7, calories: 820, image: { src: IMG.kebabPita, alt: "Large kebab bun" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-rolada",          categoryId: "kebab", name: "Kebab Rolada",          description: "Rolled flatbread, lots of meat, parsley, pickles.",
       price: { amount: 25, currency: "PLN" }, prepMinutes: 8, calories: 740, image: { src: IMG.kebabTortilla, alt: "Kebab rolada" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "kebab-talerz-maly",     categoryId: "kebab", name: "Kebab Talerz Mały",     description: "No bread — meat, salad, rice or fries.",
       price: { amount: 32, currency: "PLN" }, prepMinutes: 10, calories: 760, image: { src: IMG.kebabPlate, alt: "Small kebab plate" },
       flags: ["gluten-free"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "kebab-talerz-duzy",     categoryId: "kebab", name: "Kebab Talerz Duży",     description: "Generous plate — for those who'd rather skip the bread.",
       price: { amount: 42, currency: "PLN" }, prepMinutes: 11, calories: 980, image: { src: IMG.kebabPlate, alt: "Large kebab plate" },
       flags: ["gluten-free"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-pikantny",        categoryId: "kebab", name: "Kebab Pikantny",        description: "Marinated with extra chili. Not for the timid.",
       price: { amount: 26, currency: "PLN" }, flags: ["spicy"], prepMinutes: 9, calories: 800, image: { src: IMG.kebabTortilla, alt: "Spicy kebab" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "kebab-curry",           categoryId: "kebab", name: "Kebab Curry",           description: "House curry sauce, mango pickle, fresh coriander.",
       price: { amount: 26, currency: "PLN" }, prepMinutes: 9, calories: 820, image: { src: IMG.kebabTortilla, alt: "Curry kebab" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "shawarma-tortilla",     categoryId: "kebab", name: "Shawarma Tortilla",     description: "Slow-marinated chicken, garlic sauce, pickled cucumber.",
       price: { amount: 26, currency: "PLN" }, prepMinutes: 9, calories: 780, image: { src: IMG.shawarma, alt: "Shawarma tortilla" },
       allergens: ["Gluten", "Dairy"], modifierGroups: [MG.kebabSauce(), MG.extras()] }),
  D({ id: "shawarma-pita",         categoryId: "kebab", name: "Shawarma Pita",         description: "Same shawarma, in a soft pita.",
       price: { amount: 25, currency: "PLN" }, prepMinutes: 8, calories: 720, image: { src: IMG.shawarma, alt: "Shawarma pita" },
       allergens: ["Gluten", "Dairy"], modifierGroups: [MG.kebabSauce()] }),
  D({ id: "iskender-talerz",       categoryId: "kebab", name: "Iskender Talerz",       description: "Bread soaked in butter-tomato sauce, kebab on top, yogurt on the side.",
       price: { amount: 38, currency: "PLN" }, prepMinutes: 13, calories: 940, image: { src: IMG.kebabPlate, alt: "Iskender plate" },
       allergens: ["Gluten", "Dairy"], unavailable: true,
       modifierGroups: [MG.kebabMeat()] }),
  D({ id: "kebab-bbq",             categoryId: "kebab", name: "Kebab BBQ",             description: "Smoky BBQ sauce, crispy onions, cheddar.",
       price: { amount: 26, currency: "PLN" }, prepMinutes: 9, calories: 860, image: { src: IMG.kebabTortilla, alt: "BBQ kebab" },
       allergens: ["Gluten", "Dairy"], modifierGroups: [MG.kebabMeat(), MG.extras()] }),
  D({ id: "salatka-kebab-duzy",    categoryId: "kebab", name: "Sałatka Kebab Duży",    description: "No bread — just greens, kebab meat, tahini, pomegranate.",
       price: { amount: 32, currency: "PLN" }, flags: ["gluten-free"], prepMinutes: 10, calories: 520, image: { src: IMG.salad, alt: "Kebab salad bowl" },
       allergens: ["Sesame"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
];

const FALAFEL = [
  D({ id: "falafel-pita-maly",  categoryId: "falafel", name: "Falafel Pita Mały",  description: "Five hand-rolled falafel, hummus, salad.",
       price: { amount: 19, currency: "PLN" }, flags: ["vegetarian", "vegan"], prepMinutes: 7, calories: 540, image: { src: IMG.falafelPita, alt: "Small falafel pita" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.falafelSauce()] }),
  D({ id: "falafel-pita-duzy",  categoryId: "falafel", name: "Falafel Pita Duży",  description: "Eight hand-rolled falafel, hummus, pickled turnips, parsley.",
       price: { amount: 23, currency: "PLN" }, flags: ["vegetarian", "vegan", "featured"], prepMinutes: 8, calories: 720, image: { src: IMG.falafelPita, alt: "Large falafel pita" },
       allergens: ["Gluten", "Sesame"],
       longDescription: "The wrap we built the brand on. Eight falafel rolled by hand each morning, fried to order. Hummus, pickled turnips, fresh parsley. No shortcuts.",
       modifierGroups: [MG.falafelSauce(), MG.extras()] }),
  D({ id: "falafel-tortilla-maly", categoryId: "falafel", name: "Falafel Tortilla Mały", description: "Wrapped tortilla, four falafel, salad.",
       price: { amount: 20, currency: "PLN" }, flags: ["vegetarian", "vegan"], prepMinutes: 7, calories: 560, image: { src: IMG.falafelPita, alt: "Small falafel tortilla" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.falafelSauce()] }),
  D({ id: "falafel-tortilla-duzy", categoryId: "falafel", name: "Falafel Tortilla Duży", description: "Wrapped tortilla, seven falafel, the works.",
       price: { amount: 24, currency: "PLN" }, flags: ["vegetarian", "vegan"], prepMinutes: 8, calories: 740, image: { src: IMG.falafelPita, alt: "Large falafel tortilla" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.falafelSauce(), MG.extras()] }),
  D({ id: "falafel-bowl",       categoryId: "falafel", name: "Falafel Bowl",       description: "Couscous, roasted veg, hummus, six falafel.",
       price: { amount: 26, currency: "PLN" }, flags: ["vegetarian", "vegan"], prepMinutes: 10, calories: 680, image: { src: IMG.falafelBowl, alt: "Falafel bowl" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.falafelSauce()] }),
  D({ id: "falafel-talerz",     categoryId: "falafel", name: "Falafel Talerz",     description: "Ten falafel, two dips, salad, rice.",
       price: { amount: 32, currency: "PLN" }, flags: ["vegetarian", "vegan"], prepMinutes: 11, calories: 860, image: { src: IMG.falafelPlate, alt: "Falafel plate" },
       allergens: ["Sesame"], modifierGroups: [MG.falafelSauce()] }),
  D({ id: "falafel-sambusek",   categoryId: "falafel", name: "Falafel Sambusek",   description: "Pastry pocket stuffed with falafel and tahini.",
       price: { amount: 18, currency: "PLN" }, flags: ["vegetarian"], prepMinutes: 8, calories: 480, image: { src: IMG.falafelBowl, alt: "Sambusek" },
       allergens: ["Gluten", "Sesame"] }),
  D({ id: "falafel-burger",     categoryId: "falafel", name: "Falafel Burger",     description: "Falafel patty, sesame bun, tahini sauce, salad.",
       price: { amount: 22, currency: "PLN" }, flags: ["vegetarian"], prepMinutes: 9, calories: 640, image: { src: IMG.falafelPita, alt: "Falafel burger" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.extras()] }),
  D({ id: "salatka-falafel",    categoryId: "falafel", name: "Sałatka Falafel",    description: "Greens, six falafel, tahini-lemon, pomegranate.",
       price: { amount: 24, currency: "PLN" }, flags: ["vegetarian", "vegan", "gluten-free"], prepMinutes: 8, calories: 460, image: { src: IMG.salad, alt: "Falafel salad" },
       allergens: ["Sesame"], modifierGroups: [MG.falafelSauce()] }),
];

const TACOS = [
  D({ id: "tacos-x3",  categoryId: "tacos", name: "Tacos x3",  description: "Three soft tacos, your choice of kebab or falafel, salsa.",
       price: { amount: 29, currency: "PLN" }, flags: ["spicy", "featured"], prepMinutes: 9, calories: 620, image: { src: IMG.tacos, alt: "Three soft tacos" },
       allergens: ["Gluten"], modifierGroups: [MG.tacoFilling(), MG.spiceLevel(), MG.extras()] }),
  D({ id: "tacos-x5",  categoryId: "tacos", name: "Tacos x5",  description: "Five soft tacos, your spice level.",
       price: { amount: 42, currency: "PLN" }, flags: ["spicy"], prepMinutes: 10, calories: 940, image: { src: IMG.tacos, alt: "Five soft tacos" },
       allergens: ["Gluten"], modifierGroups: [MG.tacoFilling(), MG.spiceLevel(), MG.extras()] }),
  D({ id: "tacos-vegan-x3", categoryId: "tacos", name: "Tacos Vegan x3", description: "Three soft tacos with falafel, avocado, lime.",
       price: { amount: 27, currency: "PLN" }, flags: ["vegan", "vegetarian", "spicy"], prepMinutes: 9, calories: 540, image: { src: IMG.tacos2, alt: "Three vegan tacos" },
       allergens: ["Gluten"], modifierGroups: [MG.spiceLevel()] }),
  D({ id: "tacos-mini-x2", categoryId: "tacos", name: "Mini Tacos x2", description: "Two small tacos, perfect snack.",
       price: { amount: 18, currency: "PLN" }, prepMinutes: 7, calories: 380, image: { src: IMG.tacos2, alt: "Two mini tacos" },
       allergens: ["Gluten"], modifierGroups: [MG.tacoFilling()] }),
];

const BOX = [
  D({ id: "kapsalon-maly", categoryId: "box", name: "Kapsalon Mały", description: "Fries, kebab, melted cheese, salad, sauce.",
       price: { amount: 32, currency: "PLN" }, prepMinutes: 11, calories: 1080, image: { src: IMG.kapsalon, alt: "Small kapsalon" },
       allergens: ["Dairy"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "kapsalon-duzy", categoryId: "box", name: "Kapsalon Duży", description: "The Rotterdam classic. Fries, kebab, melted cheese, salad, sauce. Built for two.",
       price: { amount: 43, currency: "PLN" }, flags: ["featured"], prepMinutes: 12, calories: 1480, image: { src: IMG.kapsalon, alt: "Large kapsalon" },
       allergens: ["Dairy"],
       longDescription: "The dish that broke our weekend hours. Fries on the bottom, kebab on top, melted cheese over everything, finished with salad and your sauce. Built for two but most people finish it alone.",
       modifierGroups: [MG.kebabMeat(), MG.kebabSauce(), MG.extras()] }),
  D({ id: "box-strips-mala", categoryId: "box", name: "Box Strips Mała", description: "Crispy chicken strips, fries, slaw, one sauce.",
       price: { amount: 28, currency: "PLN" }, prepMinutes: 10, calories: 880, image: { src: IMG.boxStrips, alt: "Small chicken strips box" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabSauce()] }),
  D({ id: "box-strips-mega", categoryId: "box", name: "Box Strips Mega", description: "Crispy chicken strips, fries, slaw, two sauces.",
       price: { amount: 39, currency: "PLN" }, flags: ["featured"], prepMinutes: 11, calories: 1240, image: { src: IMG.boxStrips, alt: "Mega chicken strips box" },
       allergens: ["Gluten"], modifierGroups: [MG.kebabSauce(), MG.extras()] }),
  D({ id: "box-kebab-frytki", categoryId: "box", name: "Box Kebab Frytki", description: "Kebab on top of fries, sauce of choice.",
       price: { amount: 32, currency: "PLN" }, prepMinutes: 10, calories: 1020, image: { src: IMG.boxFries, alt: "Kebab and fries box" },
       modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "box-mix-grill", categoryId: "box", name: "Box Mix Grill", description: "Kebab + chicken strips + falafel + fries.",
       price: { amount: 48, currency: "PLN" }, prepMinutes: 14, calories: 1620, image: { src: IMG.boxFries, alt: "Mixed grill box" },
       allergens: ["Gluten", "Sesame"], modifierGroups: [MG.kebabSauce()] }),
  D({ id: "talerz-kebab-pelny", categoryId: "box", name: "Talerz Kebab Pełny", description: "Full plate — kebab, rice, salad, hummus, pickles.",
       price: { amount: 45, currency: "PLN" }, flags: ["gluten-free"], prepMinutes: 12, calories: 1180, image: { src: IMG.kebabPlate, alt: "Full kebab plate" },
       allergens: ["Sesame"], modifierGroups: [MG.kebabMeat(), MG.kebabSauce()] }),
  D({ id: "frytki-z-sosem", categoryId: "box", name: "Frytki z sosem", description: "Hand-cut fries with one sauce.",
       price: { amount: 14, currency: "PLN" }, flags: ["vegetarian"], prepMinutes: 6, image: { src: IMG.fries, alt: "Fries with sauce" },
       modifierGroups: [MG.kebabSauce()] }),
];

const DRINKS = [
  D({ id: "soda",        categoryId: "drinks", name: "Soda",            description: "Coca-Cola, Sprite, Fanta or Cola Zero.",
       price: { amount: 7, currency: "PLN" }, image: { src: IMG.coke, alt: "Soda" },
       modifierGroups: [MG.drinkType(), MG.drinkSize()] }),
  D({ id: "cola-classic", categoryId: "drinks", name: "Coca-Cola 0,33 L", description: "Classic.",
       price: { amount: 7, currency: "PLN" }, image: { src: IMG.coke, alt: "Coca-Cola can" } }),
  D({ id: "cola-zero",    categoryId: "drinks", name: "Coca-Cola Zero 0,33 L", description: "No sugar.",
       price: { amount: 7, currency: "PLN" }, image: { src: IMG.coke, alt: "Coca-Cola Zero can" } }),
  D({ id: "kropla",       categoryId: "drinks", name: "Kropla Beskidu 0,5 L", description: "Still or sparkling.",
       price: { amount: 6, currency: "PLN" }, image: { src: IMG.bottle, alt: "Water bottle" },
       modifierGroups: [{
         id: "water", name: "Type", required: true, min: 1, max: 1,
         options: [{ id: "still", name: "Still", priceDelta: 0, default: true }, { id: "sparkling", name: "Sparkling", priceDelta: 0 }],
       }] }),
  D({ id: "ayran",        categoryId: "drinks", name: "Ayran",          description: "Turkish salted yogurt drink. Cuts the heat.",
       price: { amount: 8, currency: "PLN" }, image: { src: IMG.ayran, alt: "Ayran" }, allergens: ["Dairy"] }),
  D({ id: "lemoniada",    categoryId: "drinks", name: "Lemoniada Domowa", description: "House lemonade with mint.",
       price: { amount: 12, currency: "PLN" }, unavailable: true, image: { src: IMG.lemonade, alt: "Homemade lemonade" } }),
  D({ id: "herbata",      categoryId: "drinks", name: "Herbata Czarna",  description: "Black tea with mint or lemon.",
       price: { amount: 6, currency: "PLN" }, image: { src: IMG.lemonade, alt: "Black tea" } }),
];

const SAUCES = [
  D({ id: "sos-side", categoryId: "sauces", name: "Sos do Frytek", description: "One side of sauce — pick your favourite.",
       price: { amount: 4, currency: "PLN" }, image: { src: IMG.sauce, alt: "Side sauce" },
       modifierGroups: [MG.kebabSauce()] }),
];

const mockDishes = [...KEBAB, ...FALAFEL, ...TACOS, ...BOX, ...DRINKS, ...SAUCES];

const getDishDetail = (id) => mockDishes.find(d => d.id === id) || null;

Object.assign(window, { mockMenuCategories, mockDishes, getDishDetail });
