// AUTO-GENERATED by scripts/generate-messages.mjs — do not edit by hand.
// Run `pnpm --filter @repo/i18n generate:messages` to regenerate after
// adding or removing message JSON files.
import type { Locale } from './locale';

import enAdminAuditLog from '../messages/en/admin/audit-log.json';
import enAdminAuthForgotPassword from '../messages/en/admin/auth/forgot-password.json';
import enAdminAuthLayout from '../messages/en/admin/auth/layout.json';
import enAdminAuthLogin from '../messages/en/admin/auth/login.json';
import enAdminAuthRegister from '../messages/en/admin/auth/register.json';
import enAdminAuthResetPassword from '../messages/en/admin/auth/reset-password.json';
import enAdminAuthVerifyEmail from '../messages/en/admin/auth/verify-email.json';
import enAdminContact from '../messages/en/admin/contact.json';
import enAdminCustomersDetail from '../messages/en/admin/customers/detail.json';
import enAdminCustomersList from '../messages/en/admin/customers/list.json';
import enAdminDashboard from '../messages/en/admin/dashboard.json';
import enAdminKds from '../messages/en/admin/kds.json';
import enAdminLayout from '../messages/en/admin/layout.json';
import enAdminMenu from '../messages/en/admin/menu.json';
import enAdminOrdersDetail from '../messages/en/admin/orders/detail.json';
import enAdminOrdersList from '../messages/en/admin/orders/list.json';
import enAdminPromotionsDetail from '../messages/en/admin/promotions/detail.json';
import enAdminPromotionsList from '../messages/en/admin/promotions/list.json';
import enAdminReportsExports from '../messages/en/admin/reports/exports.json';
import enAdminReservationsDetail from '../messages/en/admin/reservations/detail.json';
import enAdminReservationsList from '../messages/en/admin/reservations/list.json';
import enAdminRestaurant from '../messages/en/admin/restaurant.json';
import enAdminReviews from '../messages/en/admin/reviews.json';
import enAdminSettingsDeliveryZones from '../messages/en/admin/settings/delivery-zones.json';
import enAdminSettingsGeneral from '../messages/en/admin/settings/general.json';
import enAdminSettingsHolidays from '../messages/en/admin/settings/holidays.json';
import enAdminSettingsHours from '../messages/en/admin/settings/hours.json';
import enAdminStaff from '../messages/en/admin/staff.json';
import enCommon from '../messages/en/common.json';
import enErrors from '../messages/en/errors.json';
import enSharedOrderNotify from '../messages/en/shared/order-notify.json';
import enSharedOrderStatus from '../messages/en/shared/order-status.json';
import enSharedOrder from '../messages/en/shared/order.json';
import enValidation from '../messages/en/validation.json';
import enWebAccountAddresses from '../messages/en/web/account/addresses.json';
import enWebAccountLayout from '../messages/en/web/account/layout.json';
import enWebAccountLoyalty from '../messages/en/web/account/loyalty.json';
import enWebAccountNotifications from '../messages/en/web/account/notifications.json';
import enWebAccountOrderDetail from '../messages/en/web/account/order-detail.json';
import enWebAccountOrders from '../messages/en/web/account/orders.json';
import enWebAccountProfile from '../messages/en/web/account/profile.json';
import enWebAccountReferrals from '../messages/en/web/account/referrals.json';
import enWebAccountReservations from '../messages/en/web/account/reservations.json';
import enWebAccountReviews from '../messages/en/web/account/reviews.json';
import enWebAuthForgotPassword from '../messages/en/web/auth/forgot-password.json';
import enWebAuthLayout from '../messages/en/web/auth/layout.json';
import enWebAuthLogin from '../messages/en/web/auth/login.json';
import enWebAuthRegister from '../messages/en/web/auth/register.json';
import enWebAuthResetPassword from '../messages/en/web/auth/reset-password.json';
import enWebAuthVerifyEmail from '../messages/en/web/auth/verify-email.json';
import enWebLayout from '../messages/en/web/layout.json';
import enWebMarketingAbout from '../messages/en/web/marketing/about.json';
import enWebMarketingContact from '../messages/en/web/marketing/contact.json';
import enWebMarketingHome from '../messages/en/web/marketing/home.json';
import enWebMarketingLocations from '../messages/en/web/marketing/locations.json';
import enWebMarketingReservations from '../messages/en/web/marketing/reservations.json';
import enWebPublicTrack from '../messages/en/web/public/track.json';
import enWebShopCart from '../messages/en/web/shop/cart.json';
import enWebShopCheckoutSuccess from '../messages/en/web/shop/checkout-success.json';
import enWebShopCheckout from '../messages/en/web/shop/checkout.json';
import enWebShopMenuCategory from '../messages/en/web/shop/menu-category.json';
import enWebShopMenuItem from '../messages/en/web/shop/menu-item.json';
import enWebShopMenu from '../messages/en/web/shop/menu.json';
import enWebStaffAcceptInvite from '../messages/en/web/staff/accept-invite.json';

import plAdminAuditLog from '../messages/pl/admin/audit-log.json';
import plAdminAuthForgotPassword from '../messages/pl/admin/auth/forgot-password.json';
import plAdminAuthLayout from '../messages/pl/admin/auth/layout.json';
import plAdminAuthLogin from '../messages/pl/admin/auth/login.json';
import plAdminAuthRegister from '../messages/pl/admin/auth/register.json';
import plAdminAuthResetPassword from '../messages/pl/admin/auth/reset-password.json';
import plAdminAuthVerifyEmail from '../messages/pl/admin/auth/verify-email.json';
import plAdminContact from '../messages/pl/admin/contact.json';
import plAdminCustomersDetail from '../messages/pl/admin/customers/detail.json';
import plAdminCustomersList from '../messages/pl/admin/customers/list.json';
import plAdminDashboard from '../messages/pl/admin/dashboard.json';
import plAdminKds from '../messages/pl/admin/kds.json';
import plAdminLayout from '../messages/pl/admin/layout.json';
import plAdminMenu from '../messages/pl/admin/menu.json';
import plAdminOrdersDetail from '../messages/pl/admin/orders/detail.json';
import plAdminOrdersList from '../messages/pl/admin/orders/list.json';
import plAdminPromotionsDetail from '../messages/pl/admin/promotions/detail.json';
import plAdminPromotionsList from '../messages/pl/admin/promotions/list.json';
import plAdminReportsExports from '../messages/pl/admin/reports/exports.json';
import plAdminReservationsDetail from '../messages/pl/admin/reservations/detail.json';
import plAdminReservationsList from '../messages/pl/admin/reservations/list.json';
import plAdminRestaurant from '../messages/pl/admin/restaurant.json';
import plAdminReviews from '../messages/pl/admin/reviews.json';
import plAdminSettingsDeliveryZones from '../messages/pl/admin/settings/delivery-zones.json';
import plAdminSettingsGeneral from '../messages/pl/admin/settings/general.json';
import plAdminSettingsHolidays from '../messages/pl/admin/settings/holidays.json';
import plAdminSettingsHours from '../messages/pl/admin/settings/hours.json';
import plAdminStaff from '../messages/pl/admin/staff.json';
import plCommon from '../messages/pl/common.json';
import plErrors from '../messages/pl/errors.json';
import plSharedOrderNotify from '../messages/pl/shared/order-notify.json';
import plSharedOrderStatus from '../messages/pl/shared/order-status.json';
import plSharedOrder from '../messages/pl/shared/order.json';
import plValidation from '../messages/pl/validation.json';
import plWebAccountAddresses from '../messages/pl/web/account/addresses.json';
import plWebAccountLayout from '../messages/pl/web/account/layout.json';
import plWebAccountLoyalty from '../messages/pl/web/account/loyalty.json';
import plWebAccountNotifications from '../messages/pl/web/account/notifications.json';
import plWebAccountOrderDetail from '../messages/pl/web/account/order-detail.json';
import plWebAccountOrders from '../messages/pl/web/account/orders.json';
import plWebAccountProfile from '../messages/pl/web/account/profile.json';
import plWebAccountReferrals from '../messages/pl/web/account/referrals.json';
import plWebAccountReservations from '../messages/pl/web/account/reservations.json';
import plWebAccountReviews from '../messages/pl/web/account/reviews.json';
import plWebAuthForgotPassword from '../messages/pl/web/auth/forgot-password.json';
import plWebAuthLayout from '../messages/pl/web/auth/layout.json';
import plWebAuthLogin from '../messages/pl/web/auth/login.json';
import plWebAuthRegister from '../messages/pl/web/auth/register.json';
import plWebAuthResetPassword from '../messages/pl/web/auth/reset-password.json';
import plWebAuthVerifyEmail from '../messages/pl/web/auth/verify-email.json';
import plWebLayout from '../messages/pl/web/layout.json';
import plWebMarketingAbout from '../messages/pl/web/marketing/about.json';
import plWebMarketingContact from '../messages/pl/web/marketing/contact.json';
import plWebMarketingHome from '../messages/pl/web/marketing/home.json';
import plWebMarketingLocations from '../messages/pl/web/marketing/locations.json';
import plWebMarketingReservations from '../messages/pl/web/marketing/reservations.json';
import plWebPublicTrack from '../messages/pl/web/public/track.json';
import plWebShopCart from '../messages/pl/web/shop/cart.json';
import plWebShopCheckoutSuccess from '../messages/pl/web/shop/checkout-success.json';
import plWebShopCheckout from '../messages/pl/web/shop/checkout.json';
import plWebShopMenuCategory from '../messages/pl/web/shop/menu-category.json';
import plWebShopMenuItem from '../messages/pl/web/shop/menu-item.json';
import plWebShopMenu from '../messages/pl/web/shop/menu.json';
import plWebStaffAcceptInvite from '../messages/pl/web/staff/accept-invite.json';

const EN_MESSAGES = {
  admin: {
    auditLog: enAdminAuditLog,
    auth: {
      forgotPassword: enAdminAuthForgotPassword,
      layout: enAdminAuthLayout,
      login: enAdminAuthLogin,
      register: enAdminAuthRegister,
      resetPassword: enAdminAuthResetPassword,
      verifyEmail: enAdminAuthVerifyEmail,
    },
    contact: enAdminContact,
    customers: {
      detail: enAdminCustomersDetail,
      list: enAdminCustomersList,
    },
    dashboard: enAdminDashboard,
    kds: enAdminKds,
    layout: enAdminLayout,
    menu: enAdminMenu,
    orders: {
      detail: enAdminOrdersDetail,
      list: enAdminOrdersList,
    },
    promotions: {
      detail: enAdminPromotionsDetail,
      list: enAdminPromotionsList,
    },
    reports: {
      exports: enAdminReportsExports,
    },
    reservations: {
      detail: enAdminReservationsDetail,
      list: enAdminReservationsList,
    },
    restaurant: enAdminRestaurant,
    reviews: enAdminReviews,
    settings: {
      deliveryZones: enAdminSettingsDeliveryZones,
      general: enAdminSettingsGeneral,
      holidays: enAdminSettingsHolidays,
      hours: enAdminSettingsHours,
    },
    staff: enAdminStaff,
  },
  common: enCommon,
  errors: enErrors,
  shared: {
    orderNotify: enSharedOrderNotify,
    orderStatus: enSharedOrderStatus,
    order: enSharedOrder,
  },
  validation: enValidation,
  web: {
    account: {
      addresses: enWebAccountAddresses,
      layout: enWebAccountLayout,
      loyalty: enWebAccountLoyalty,
      notifications: enWebAccountNotifications,
      orderDetail: enWebAccountOrderDetail,
      orders: enWebAccountOrders,
      profile: enWebAccountProfile,
      referrals: enWebAccountReferrals,
      reservations: enWebAccountReservations,
      reviews: enWebAccountReviews,
    },
    auth: {
      forgotPassword: enWebAuthForgotPassword,
      layout: enWebAuthLayout,
      login: enWebAuthLogin,
      register: enWebAuthRegister,
      resetPassword: enWebAuthResetPassword,
      verifyEmail: enWebAuthVerifyEmail,
    },
    layout: enWebLayout,
    marketing: {
      about: enWebMarketingAbout,
      contact: enWebMarketingContact,
      home: enWebMarketingHome,
      locations: enWebMarketingLocations,
      reservations: enWebMarketingReservations,
    },
    public: {
      track: enWebPublicTrack,
    },
    shop: {
      cart: enWebShopCart,
      checkoutSuccess: enWebShopCheckoutSuccess,
      checkout: enWebShopCheckout,
      menuCategory: enWebShopMenuCategory,
      menuItem: enWebShopMenuItem,
      menu: enWebShopMenu,
    },
    staff: {
      acceptInvite: enWebStaffAcceptInvite,
    },
  },
} as const;

const PL_MESSAGES = {
  admin: {
    auditLog: plAdminAuditLog,
    auth: {
      forgotPassword: plAdminAuthForgotPassword,
      layout: plAdminAuthLayout,
      login: plAdminAuthLogin,
      register: plAdminAuthRegister,
      resetPassword: plAdminAuthResetPassword,
      verifyEmail: plAdminAuthVerifyEmail,
    },
    contact: plAdminContact,
    customers: {
      detail: plAdminCustomersDetail,
      list: plAdminCustomersList,
    },
    dashboard: plAdminDashboard,
    kds: plAdminKds,
    layout: plAdminLayout,
    menu: plAdminMenu,
    orders: {
      detail: plAdminOrdersDetail,
      list: plAdminOrdersList,
    },
    promotions: {
      detail: plAdminPromotionsDetail,
      list: plAdminPromotionsList,
    },
    reports: {
      exports: plAdminReportsExports,
    },
    reservations: {
      detail: plAdminReservationsDetail,
      list: plAdminReservationsList,
    },
    restaurant: plAdminRestaurant,
    reviews: plAdminReviews,
    settings: {
      deliveryZones: plAdminSettingsDeliveryZones,
      general: plAdminSettingsGeneral,
      holidays: plAdminSettingsHolidays,
      hours: plAdminSettingsHours,
    },
    staff: plAdminStaff,
  },
  common: plCommon,
  errors: plErrors,
  shared: {
    orderNotify: plSharedOrderNotify,
    orderStatus: plSharedOrderStatus,
    order: plSharedOrder,
  },
  validation: plValidation,
  web: {
    account: {
      addresses: plWebAccountAddresses,
      layout: plWebAccountLayout,
      loyalty: plWebAccountLoyalty,
      notifications: plWebAccountNotifications,
      orderDetail: plWebAccountOrderDetail,
      orders: plWebAccountOrders,
      profile: plWebAccountProfile,
      referrals: plWebAccountReferrals,
      reservations: plWebAccountReservations,
      reviews: plWebAccountReviews,
    },
    auth: {
      forgotPassword: plWebAuthForgotPassword,
      layout: plWebAuthLayout,
      login: plWebAuthLogin,
      register: plWebAuthRegister,
      resetPassword: plWebAuthResetPassword,
      verifyEmail: plWebAuthVerifyEmail,
    },
    layout: plWebLayout,
    marketing: {
      about: plWebMarketingAbout,
      contact: plWebMarketingContact,
      home: plWebMarketingHome,
      locations: plWebMarketingLocations,
      reservations: plWebMarketingReservations,
    },
    public: {
      track: plWebPublicTrack,
    },
    shop: {
      cart: plWebShopCart,
      checkoutSuccess: plWebShopCheckoutSuccess,
      checkout: plWebShopCheckout,
      menuCategory: plWebShopMenuCategory,
      menuItem: plWebShopMenuItem,
      menu: plWebShopMenu,
    },
    staff: {
      acceptInvite: plWebStaffAcceptInvite,
    },
  },
} as const;

export type AppMessages = typeof EN_MESSAGES;

/**
 * Returns the merged message tree for `locale`, used by next-intl on web/admin.
 * The shape is type-locked to the English tree; `i18n.test.ts` verifies that
 * EN and PL key sets are identical at runtime.
 */
export function loadMessages(locale: Locale): AppMessages {
  return (locale === 'pl' ? PL_MESSAGES : EN_MESSAGES) as AppMessages;
}
